{% set version = "3.0.10" %}

package:
  name: pyathena
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyAthena/PyAthena-{{ version }}.tar.gz
  sha256: 1ef983d478bc182c2ea31d75bf4fd5755425985e5da4f8e181235f2d2733e536

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.1.0
  run:
    - python >=3.8.1
    - boto3 >=1.26.4
    - botocore >=1.29.4
    - tenacity >=4.1.0
    - fsspec *
  run_constrained:
    - sqlalchemy >=1.0.0
    - pandas >=1.3.0
    - pyarrow >=7.0.0
    - fastparquet >=0.4.0

test:
  imports:
    - pyathena

about:
  home: https://github.com/laughingman7743/PyAthena/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python DB API 2.0 (PEP 249) compliant client for Amazon Athena
  dev_url: https://github.com/laughingman7743/PyAthena/

extra:
  recipe-maintainers:
    - JorgeGarciaIrazabal
    - mariusvniekerk
