{% set name = "pyathena" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyathena-{{ version }}.tar.gz
  sha256: 09b67e2f04d30a489a936addf5792c92cac4e59a249dd8bfcf69192fced3972f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.1
    - hatchling
    - pip
  run:
    - python >=3.8.1
    - boto3 >=1.26.4
    - botocore >=1.29.4
    - tenacity >=4.1.0
    - fsspec

test:
  imports:
    - pyathena
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/laughingman7743/PyAthena/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python DB API 2.0 (PEP 249) compliant client for Amazon Athena
  dev_url: https://github.com/laughingman7743/PyAthena/

extra:
  recipe-maintainers:
    - xylar
    - JorgeGarciaIrazabal
    - mariusvniekerk
