{% set name = "PyAthena" %}
{% set version = "1.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 280c3268ef8ae13f607d62b7ee0740feecf7de7ae8898d2be72add80762da188

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - boto3 >=1.4.4
    - botocore >=1.5.52
    - future
    - futures  # [py27]
    - python
    - setuptools
    - tenacity >=4.1.0

test:
  imports:
    - pyathena
    - tests
  requires:
    - pytest >=3.5
    - pytest-cov
    - pytest-flake8 >=1.0.1
    - sqlalchemy >=1.0.0,<1.3.0

about:
  home: https://github.com/laughingman7743/PyAthena/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python DB API 2.0 (PEP 249) compliant client for Amazon Athena
  dev_url: https://github.com/laughingman7743/PyAthena/

extra:
  recipe-maintainers:
    - JorgeGarciaIrazabal
    - mariusvniekerk
